spring.datasource.url=jdbc:postgresql://localhost:5432/nutrition_app
spring.datasource.username=postgres
spring.datasource.password=123

server.port=5000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true